language: c
sudo: false

addons:
  apt:
    packages:
    - aspcud
    - libglpk-dev

before_install:
    - bash -ex .travis-ci.sh prepare
install:
    - bash -ex .travis-ci.sh install

cache:
    directories:
    - $HOME/.opam.bootstrap

script:
    - bash -ex .travis-ci.sh build

matrix:
  include:
    - os: linux
      env: OCAML_VERSION=4.06.0 OPAM_TEST=1 EXTERNAL_SOLVER=
    - os: linux
      env: OCAML_VERSION=4.06.0 OPAM_TEST=1 EXTERNAL_SOLVER=aspcud
    - os: linux
      env: OCAML_VERSION=4.03.0 OPAM_TEST=
    - os: linux
      env: OCAML_VERSION=4.02.3 OPAM_TEST=
    - os: linux
      env: OCAML_VERSION=4.05.0 OPAM_TEST=
    - os: linux
      env: OCAML_VERSION=4.06.0 OPAM_TEST=
    - os: osx
      env: OCAML_VERSION=4.06.0 OPAM_TEST=1 EXTERNAL_SOLVER=
    - os: osx
      env: OCAML_VERSION=4.03.0 OPAM_TEST=
notifications:
  email:
    - opam-commits@lists.ocaml.org
  irc:
    - "chat.freenode.net#opam"
