language: c
script: bash -ex .travis-ci.sh
matrix:
  include:
    - os: linux
      env: OCAML_VERSION=4.03.0 OPAM_TEST=1 EXTERNAL_SOLVER=
    - os: linux
      env: OCAML_VERSION=4.03.0 OPAM_TEST=1 EXTERNAL_SOLVER=aspcud
    - os: linux
      env: OCAML_VERSION=4.03.0 OPAM_TEST=
    - os: linux
      env: OCAML_VERSION=4.02.3 OPAM_TEST=
    - os: linux
      env: OCAML_VERSION=4.01.0 OPAM_TEST=
    - os: osx
      env: OCAML_VERSION=4.03.0 OPAM_TEST=1 EXTERNAL_SOLVER=
    - os: osx
      env: OCAML_VERSION=4.03.0 OPAM_TEST=
  allow_failures:
    - os: osx
      env: OCAML_VERSION=4.03.0 OPAM_TEST=1 EXTERNAL_SOLVER=
notifications:
  email:
    - opam-commits@lists.ocaml.org
  irc:
    - "chat.freenode.net#opam"
