platform:
    - x86

environment:
  global:
    CYG_ROOT: C:/cygwin
    CYG_CACHE: C:/cygwin/var/cache/setup
    CYG_MIRROR: http://mirrors.kernel.org/sourceware/cygwin/
  matrix:
    -
      CYG_ARCH: x86

init:
  - 'echo System architecture: %PLATFORM%'

install:
  - 'appveyor DownloadFile http://cygwin.com/setup-%CYG_ARCH%.exe -FileName setup.exe'
  - 'setup.exe -qnNdO -R "%CYG_ROOT%" -s "%CYG_MIRROR%" -l "%CYG_CACHE%" -P make -P git -P gcc-core -P ocaml -P ocaml-camlp4 -P ocaml-compiler-libs -P libncurses-devel -P unzip >NUL'
  - 'setup.exe -qnNdO -R "%CYG_ROOT%" -s "%CYG_MIRROR%" -l "%CYG_CACHE%" -P libmpfr-devel -P patch -P flexdll >NUL'
  - '%CYG_ROOT%/bin/bash -lc "cygcheck -dc cygwin"'

build_script:
  - '%CYG_ROOT%/bin/bash -lc "cd \"$OLDPWD\" && env DJDIR="workaround" ./configure && make lib-ext && make && make install"'
  - '%CYG_ROOT%/bin/bash -lc "opam init -y -a"'
  - '%CYG_ROOT%/bin/bash -lc "opam config env"'
  - '%CYG_ROOT%/bin/bash -lc "opam install -y -v ocamlfind"'
