platform:
    - x64

image: Visual Studio 2017

environment:
  global:
    CYG_ROOT: cygwin64
    CYG_ARCH: x86_64
    OCAML_PORT:
    CYG_CACHE: C:/cygwin/var/cache/setup
    CYG_MIRROR: http://mirrors.kernel.org/sourceware/cygwin/
    DEP_MODE: lib-ext
  matrix:
    - CYG_ROOT: cygwin
      CYG_ARCH: x86
    - CYG_ROOT: cygwin64
      CYG_ARCH: x86_64
      DEP_MODE: lib-pkg
    - OCAML_PORT: msvc
      DEP_MODE: lib-pkg
    - OCAML_PORT: msvc64
    - OCAML_PORT: mingw
    - OCAML_PORT: mingw64
      DEP_MODE: lib-pkg

cache:
  - C:\projects\opam\bootstrap
  - C:\projects\opam\src_ext\archives

init:
  - "echo System architecture: %PLATFORM%"

install:
  - call "%APPVEYOR_BUILD_FOLDER%\appveyor_build.cmd" install

build_script:
  - call "%APPVEYOR_BUILD_FOLDER%\appveyor_build.cmd" build

test_script:
  - call "%APPVEYOR_BUILD_FOLDER%\appveyor_build.cmd" test
